# Generated by Django 4.0.4 on 2022-06-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='pelicula',
            new_name='nombre',
        ),
    ]
