# Generated by Django 4.0.4 on 2022-06-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_usuario_rename_pelicula_pelicula_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('plataforma', models.CharField(max_length=30)),
                ('puntuacion', models.IntegerField()),
                ('comentarios', models.CharField(max_length=300)),
            ],
        ),
    ]
