# Generated by Django 4.0.4 on 2022-07-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_portada'),
        ),
        migrations.AddField(
            model_name='serie',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_portada'),
        ),
    ]
