# Generated by Django 4.0.4 on 2022-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_delete_usuario_pelicula_portada_serie_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fecha',
            field=models.DateField(default=(2000, 1, 1)),
        ),
    ]
