# Generated by Django 4.0.4 on 2022-07-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_remove_pelicula_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='portada',
            field=models.ImageField(null=True, upload_to='imagenes_portada'),
        ),
    ]
