# Generated by Django 4.0.4 on 2022-07-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_serie_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(null=True, upload_to='imagenes_portada'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_portada'),
        ),
    ]
